services:
  # Banco de dados MySQL
  mysql_autorizador:
    image: mysql:8.4.0
    container_name: mysql_autorizador
    environment:
      MYSQL_DATABASE: autorizadordb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_TCP_PORT: 3306
    ports:
      - "3308:3306"
    volumes:
      - mysql_autorizador_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

  app:
    build: .
    container_name: autorizador-app
    ports:
      - "3003:3003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_autorizador:3306/autorizadordb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
    networks:
      - app-network
    depends_on:
      mysql_autorizador:
        condition: service_healthy

volumes:
  mysql_autorizador_data:

networks:
  app-network:
    driver: bridge
